#!/bin/bash
. /etc/apache2/envvars

. /etc/default/apache-htcacheclean

export TZ="${NAGIOS_TIMEZONE}"

if ! [ "${NAGIOS_FQDN}" = "" ]; then
    echo "ServerName ${NAGIOS_FQDN}" > /etc/apache2/conf-available/servername.conf
fi

exec /usr/sbin/apache2 -D NO_DETACH
