#!/bin/bash
. /etc/apache2/envvars

. /etc/default/apache-htcacheclean

export TZ="${NAGIOS_TIMEZONE}"

test -f /usr/local/share/confs/apache-nrdp.conf || \
  cp /usr/local/share/default_confs/apache-nrdp.conf /usr/local/share/confs/apache-nrdp.conf

exec /usr/sbin/apache2 -D NO_DETACH
