#!/bin/bash
. /etc/apache2/envvars

. /etc/default/apache-htcacheclean

export TZ="${NAGIOS_TIMEZONE}"

test -f /opt/CustomApacheFiles/apache-extra.conf || touch /opt/CustomApacheFiles/apache-extra.conf

exec /usr/sbin/apache2 -D NO_DETACH
